name: Build documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@bcff59fca682130d2e7271ca8589911b7ac0b8bf  # main
    with:
      commit_sha: ${{ github.sha }}
      package: agents-course
      package_name: agents-course
      path_to_docs: agents-course/units/
      additional_args: --not_python_module
      languages: en zh-CN ru-RU vi es ko fr
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
